### PR TITLE
Multiprocessing capabilities for the function evaluation

### PR DESCRIPTION
**Pull request by saullocastro**

### CODE REVIEW

**Comment by saullocastro** [comment]
@rmsolgi please, check it out and let me know what you think about this idea

**Comment by allanchan339** [comment]
I am also looking for multiprocessing capabilities for fitness calculation

**Comment by allanchan339** [comment]
Did u try to use windows machine to test this code? It seems you may need to fix some bugs for AssertionError: daemonic processes are not allowed to have children

**Comment by saullocastro** [comment]
I tested only on windows.

**Comment by allanchan339** [comment]
```
import numpy as np
import math
from geneticalgorithm import geneticalgorithm as ga


def f(X):
    dim = len(X)
    a = 0.5
    b = 3
    OF = 0
    for i in range(0, dim):
        t1 = 0
        for k in range(0, 21):
            t1 += (a**k) * math.cos((2 * math.pi * (b**k)) * (X[i] + 0.5))
        OF += t1
    t2 = 0
    for k in range(0, 21):
        t2 += (a**k) * math.cos(math.pi * (b**k))
    OF -= dim * t2
    return OF


varbound = np.array([[-0.5, 0.5]] * 2)

algorithm_param = {'max_num_iteration': 1000,
                   'population_size': 100,
                   'mutation_probability': 0.1,
                   'elit_ratio': 0.01,
                   'crossover_probability': 0.5,
                   'parents_portion': 0.3,
                   'crossover_type': 'uniform',
                   'max_iteration_without_improv': None,
                   'multiprocessing_ncpus': 2,
                   'multiprocessing_engine': None
                   }

model = ga(function = f, dimension = 2,
           variable_type = 'real',
           variable_boundaries = varbound,
           algorithm_parameters = algorithm_param)

model.run()

```

I am testing this code only, running on my windows. 
The console output is as follows,
```
using Python  multiprocessing
using Python  multiprocessing
using Python  multiprocessing
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ZERO\PycharmProjects\backtest\test.py", line 44, in <module>
    model.run()
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\site-packages\geneticalgorithm\geneticalgorithm.py", line 315, in run
    pool = Pool(self.multiprocessing_ncpus)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 105, in spawn_main
    _check_not_importing_main()
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    exitcode = _main(fd)
  File "C:\Users\ZERO\Anaconda3\envs\untitled\lib\multiprocessing\spawn.py", line 114, in _main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```
and so on.
Interestingly, this code run properly in linux machine.
Any idea for this runtime error?

**Comment by saullocastro** [comment]
It seems that your main code is not protected. Is your main code inside a
if __name__ == "__main__" block?

**Comment by rmsolgi** [comment]
> @rmsolgi please, check it out and let me know what you think about this idea

Awesome, thank you for your update! Primarily I avoided to add multiprocessing being afraid of possible issues on different machines but this is definitely necessary and useful to have. Thank you!

**Comment by saullocastro** [comment]
@rmsolgi you are welcome. If you have no comments and agree with the pull request, you can merge this branch.

**Comment by Mexflubber** [comment]
Found an issue with this branch. All the elements of first generation contain the same values.

**Pull request closed without merging**
